
// -------------- INTERUPT CONSTANTS --------------

.label CURRENT_RASTER_LINE = $d012

.label INTERRUPT_STATUS = $d019
.label INTERRUPT_CONTROL = $d01a

.label INTERRUPT_SERVICE_LO = $0314
.label INTERRUPT_SERVICE_HI = $0315

.label INTERRUPT_CONTROL_AND_STATUS_CIA_1 = $dc0d
.label INTERRUPT_CONTROL_AND_STATUS_CIA_2 = $dd0d

.label INTERRUPT_RETURN = $ea81


